local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint

   # The frequency in Hz for the map to be updated.
   # Default values 
   update_frequency: 5.0
   publish_frequency: 0.0

   # The size and resolution of the map in meters.
   width: 5.0
   height: 5.0
   resolution: 0.02

   static_map: false

   # Specifies the delay in transform (tf) data that is tolerable in seconds. 
   # This parameter serves as a safeguard to losing a link in the tf tree while still allowing an amount 
   # of latency the user is comfortable with to exist in the system. 
   # For example, a transform being 0.2 seconds out-of-date may be tolerable, 
   # but a transform being 8 seconds out of date is not.
   #
   transform_tolerance: 0.2

   rolling_window: true
