TrajectoryPlannerROS:

  holonomic_robot: false
  # The amount of time to forward-simulate trajectories in seconds
  sim_time: 1.0

  publish_cost_grip_pc: true

  # The weighting for how much the controller should stay close to the path it was given, 
  # maximal possible value is 5.0
  pdist_scale: 0.6

  # The weighting for how much the controller should attempt to reach its local goal, also controls speed
  gdist_scale: 0.8
