global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint

   # The frequency in Hz for the map to be updated.
   # Default values 
   update_frequency: 5.0
   publish_frequency: 0.0

   # The size and resolution of the map in meters.
   width: 10.0
   height: 10.0
   resolution: 0.05

   static_map: true
   rolling_window: false
